Courses/Software Technologies/AspNet MVC/Exam/Web/HikingPlanAndRescue.Web/Controllers/IdeasController.cs
namespace VoiceSystem.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Data.Models;
    using Infrastructure.Filters;
    using VoiceSystem.Services.Data.Contracts;
    using VoiceSystem.Web.Infrastructure.Mapping;
    using VoiceSystem.Web.ViewModels.Ideas;

    public class IdeasController : BaseController
    {
        private const int PageSize = 3;
        private const int CommentsPageSize = 4;
        private IIdeasService ideas;
        private ICommentsService comments;

        public IdeasController(IIdeasService ideas, ICommentsService comments)
        {
            this.ideas = ideas;
            this.comments = comments;
        }

        public ActionResult Index(string query, int id = 1)
        {
            int page = id - 1;
            if (query == "")
            {
                query = null;
            }

            var allIdeas = this.ideas.
                GetAllWithPaging(page, PageSize)
                .Where(x => query == null || x.Description.IndexOf(query) >= 0)
                .To<IdeaViewModel>();
            //var ideasCount = this.ideas.GetAll().Count();
            var ideasCount = this.ideas.GetAll().Count();
            var pageCount = (int)Math.Ceiling(ideasCount / (decimal)PageSize);

            var ideaIndexModel = new IdeaIndexViewModel()
            {
                CreateModel = new IdeaCreateViewModel(),
                Ideas = allIdeas,
                PageCount = pageCount,
                Page = id
            };

            return this.View(ideaIndexModel);
        }

        [HttpPost]
        [AjaxRequestOnly]
        public ActionResult Create(IdeaCreateViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Json(new
                {
                    error = "Invalid model"
                });
            }

            var idea = this.Mapper.Map<Idea>(model);
            idea.UserIp = this.UserIp;
            this.ideas.Add(idea);
            return this.Json("ok");
        }

        public ActionResult Details(int id, int page = 1)
        {
            var idea = this.ideas.GetById(id);
            var ideaModel = this.Mapper.Map<IdeaDetailsViewModel>(idea);
            //var ideaComments = this.comments.GetAllIdeaCommentsWithPaging(page - 1, CommentsPageSize, idea.Id).To<CommentViewModel>();
            var ideaComments = idea.Comments
                .OrderByDescending(x => x.CreatedOn)
                .Skip((page - 1) * CommentsPageSize)
                .Take(CommentsPageSize)
                .AsQueryable()
                .To<CommentViewModel>()
                .ToList();

            var commentsCount = idea.Comments.Count();
            var pageCount = (int)Math.Ceiling(commentsCount / (decimal)CommentsPageSize);

            var pageModel = new IdeaDetailsPageViewModel()
            {
                Comments = ideaComments,
                Idea = ideaModel,
                Page = page,
                PageCount = pageCount
            };

            return this.View(pageModel);
        }

        [HttpPost]
        [AjaxRequestOnly]
        public ActionResult AddComment(CommentCreateViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Json(new
                {
                    error = "Invalid model"
                });
            }

            var comment = this.Mapper.Map<Comment>(model);
            comment.UserIp = this.UserIp;
            this.comments.Add(comment);
            return this.Json("ok");
        }
    }
}

Courses/Software Technologies/AspNet MVC/Exam/Web/HikingPlanAndRescue.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kendo/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    @RenderSection("styles", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @Html.Partial("_PrivateMenu")
                    }
                </ul>

                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </div>

    <div class="container body-content">

        @Html.Partial("_Notifications")

        @RenderBody()

    </div>

    <hr />
    <footer class="container">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendo")

    @RenderSection("scripts", required: false)

</body>
</html>

Courses/Software Technologies/AspNet MVC/Exam/Web/HikingPlanAndRescue.Web/Views/Shared/_PrivateMenu.cshtml
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Admin Stuff <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li>
            @Html.ActionLink("Admin Comments", "Index", "Comments", new { area = "admin" }, null)
        </li>
        <li>
            @Html.ActionLink("Admin Ideas", "Index", "Ideas", new { area = "admin" }, null)
        </li>
    </ul>
</li>