Courses/Software Technologies/AspNet MVC/HW/02-ASP.NET MVC Essentials Homework/Task3-BikeShop/BikeShop/Models/ArticleViewModel.cs
namespace BikeShop.Models
{
    public class ArticleViewModel
    {
        public int Id{ get; set; }

        public string Title { get; set; }

        public string Content { get; set; }
    }
}

Courses/Software Technologies/AspNet MVC/HW/02-ASP.NET MVC Essentials Homework/Task3-BikeShop/BikeShop/Areas/Shop/Controllers/OperationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BikeShop.Areas.Shop.Controllers
{
    public class OperationsController : Controller
    {
        // GET: Shop
        public ActionResult Buy()
        {
            return View();
        }

        public ActionResult Sell()
        {
            return View();
        }
    }
}

Courses/Software Technologies/AspNet MVC/HW/02-ASP.NET MVC Essentials Homework/Task3-BikeShop/BikeShop/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BikeShop.Models;

namespace BikeShop.Controllers
{
    public class BlogController : Controller
    {
        IList<ArticleViewModel> data = new List<ArticleViewModel>();

        public BlogController()
        {
            for (int i = 0; i < 20; i++)
            {
                this.data.Add(new ArticleViewModel() {Id = i, Title = $"Article {i}", Content = $"Article {i} content..." });
            }
        }

        // GET: Blog
        public ActionResult Index()
        {
            return View(data);
        }

        public ActionResult Article(int id)
        {
            return View(data[id]);
        }
    }
}

Courses/Software Technologies/AspNet MVC/HW/02-ASP.NET MVC Essentials Homework/Task3-BikeShop/BikeShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BikeShop.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "This is a simple bike shop app.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Find us on Vitosha, Bai Krystio.";

            return View();
        }
    }
}

Courses/Software Technologies/AspNet MVC/HW/02-ASP.NET MVC Essentials Homework/Task3-BikeShop/BikeShop/Areas/Shop/Views/Operations/Buy.cshtml
@{
    ViewBag.Title = "Products list";
}

<h2>@ViewBag.Title</h2>

<div class="container">
    @for (int i = 0; i < 10; i++)
    {
        <div class="pull-left clearfix">
            <h3>Item @i</h3>
            <h4>Details:</h4>
            <p>Item @i details description...</p>
            <p>Price: @(i * 100)</p>
        </div>
    }
</div>

Courses/Software Technologies/AspNet MVC/HW/02-ASP.NET MVC Essentials Homework/Task3-BikeShop/BikeShop/Areas/Shop/Views/Operations/Sell.cshtml
@{
    ViewBag.Title = "Sell";
}

<h2>Sell</h2>

<p>Sell your item here.</p>

Courses/Software Technologies/AspNet MVC/HW/02-ASP.NET MVC Essentials Homework/Task3-BikeShop/BikeShop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>No additional info!</p>

Courses/Software Technologies/AspNet MVC/HW/02-ASP.NET MVC Essentials Homework/Task3-BikeShop/BikeShop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Vitosha Mountain<br />
    Bai Krystio Intermmediate lift station<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@BikeShop.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@BikeShop.com</a>
</address>

Courses/Software Technologies/AspNet MVC/HW/02-ASP.NET MVC Essentials Homework/Task3-BikeShop/BikeShop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Welcome to Bike Shop</h1>
    <p class="lead">Bike Shop Krystio is leader in bike sells in Sofia</p>
</div>

<div class="container">
    <div class="well-lg pull-left">
        <h2>Shop</h2>
        <ul class="list-unstyled">
            <li class="lead">
                @Html.ActionLink("Buy", "Buy", "Operations", new { area = "Shop" }, null)
            </li>
            <li class="lead">
                @Html.ActionLink("Sell", "Sell", "Operations", new { area = "Shop" }, null)
            </li>
        </ul>
    </div>
    <div class="well-lg pull-left">
        <h2>Info</h2>
        <p class="lead pull-left">
            @Html.ActionLink("See our blog", "Index", "Blog")
        </p>
    </div>
</div>